// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByV39J21FoY3qMgWC2dI4ObQpJImjdWCo',
    appId: '1:894827062659:web:905c3f4dbc760b7b5d82b6',
    messagingSenderId: '894827062659',
    projectId: 'testing-cli-850dc',
    authDomain: 'testing-cli-850dc.firebaseapp.com',
    storageBucket: 'testing-cli-850dc.firebasestorage.app',
    measurementId: 'G-S7P8ZP7RQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM6qDWTtz49SyKe5PKYjwthJxMDGy-lVA',
    appId: '1:894827062659:android:1d7e09a7ae7470145d82b6',
    messagingSenderId: '894827062659',
    projectId: 'testing-cli-850dc',
    storageBucket: 'testing-cli-850dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiTl-OP2akM-ez7jAa7RS7ZteaHqeKqEY',
    appId: '1:894827062659:ios:6cf4ac3d414365c45d82b6',
    messagingSenderId: '894827062659',
    projectId: 'testing-cli-850dc',
    storageBucket: 'testing-cli-850dc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSeriesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiTl-OP2akM-ez7jAa7RS7ZteaHqeKqEY',
    appId: '1:894827062659:ios:6cf4ac3d414365c45d82b6',
    messagingSenderId: '894827062659',
    projectId: 'testing-cli-850dc',
    storageBucket: 'testing-cli-850dc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSeriesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByV39J21FoY3qMgWC2dI4ObQpJImjdWCo',
    appId: '1:894827062659:web:33ab5513ddfe641f5d82b6',
    messagingSenderId: '894827062659',
    projectId: 'testing-cli-850dc',
    authDomain: 'testing-cli-850dc.firebaseapp.com',
    storageBucket: 'testing-cli-850dc.firebasestorage.app',
    measurementId: 'G-855V3Z5BDJ',
  );
}
